networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres/data
    networks:
      custom:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sa
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongo/data
    networks:
      custom:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      custom:
  auction-svc:
    image: trycatchlearn/auction-svc:lastest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;Database=auction;User Id=sa;Password=12345
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - rabbitmq
      - postgres
    networks:
      custom:
  search-svc:
    image: trycatchlearn/search-svc:lastest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://sa:12345@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      custom:
  identity-svc:
    image: trycatchlearn/identity-svc:lastest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://app.carstiestest.com
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;Database=identity;User Id=sa;Password=12345
      - VIRTUAL_HOST=id.carstiestest.com
    depends_on:
      - postgres
    networks:
      custom:
        ipv4_address: 10.5.0.200
  gateway-svc:
    image: trycatchlearn/gateway-svc:lastest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://app.carstiestest.com
      - VIRTUAL_HOST=api.carstiestest.com
    networks:
      custom:
  bid-svc:
    image: trycatchlearn/bid-svc:lastest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnectionString=mongodb://sa:12345@mongodb
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777
    ports:
      - 7003:80
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      custom:
  notify-svc:
    image: trycatchlearn/notify-svc:lastest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq
    networks:
      custom:
  web-app:
    image: trycatchlearn/web-app
    build:
      context: .
      dockerfile: fontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    extra_hosts:
      - id.carstiestest.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=somgthingreallyreallysecret
      - NEXTAUTH_URL=http://app.carstiestest.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc
      - ID_URL=http://id.carstiestest.com
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc/notifications
      - VIRTUAL_HOST=app.carstiestest.com
      - VIRTUAL_PORT=3000 
    networks:
      custom:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./devcerts:/etc/nginx/certs

